### ISSUE TITLE
How to construct fourth-order tensors?

### ISSUE THREAD

**Issue by singularitti** [iitis/SymmetricTensors.jl#13]
I am sorry I did not understand your code without reading the associated paper. May I ask if we can create fourth-order tensors in this package, especially the symmetric ones?

**Comment by kdomino** [comment]
You can convert the symmetric 4-th dimensional array to this format.
As symmetric tensor we understand x[i,j,k,l] = x [j,i,k,l] = x[k,i,j,l] = .... there are 4! equities. There is also possibility to create random symmetric tensor (i.e. with random elements). In the case of 4-th order tensor of size 2 x 2 x 2 x 2 the generator would be:

```
julia> using Random;

julia> x = rand(SymmetricTensor{Float64, 4}, 2);

```

besides I will take a look on the pull request.

**Comment by singularitti** [comment]
So the `2` in the code means the `2` in "2 x 2 x 2 x 2", right?

**Comment by kdomino** [comment]
right, I corrected a bit example in Readme

**Comment by kdomino** [comment]
So we can close the issue?

**Comment by singularitti** [comment]
Sure! Sorry I forgot.
