### ISSUE TITLE
SymmetricTensor accessors should be cleaned-up

### ISSUE THREAD

**Issue by lpawela** [iitis/SymmetricTensors.jl#5]
Following changes to symmetric tensors access functions should be made:

1. `getindex(st::SymmetricTensor, mulind...)` should return tensor element in the same as an `Array` would.
1. `accesnotord(st::SymmetricTensor, mulind::Tuple)` rename to `getblock(st::SymmetricTensor, mulind::Tuple)`.
1. add `getblock(st::SymmetricTensor, mulind...)`.

**Comment by kdomino** [comment]
getindex, and accessors cleanded-up and corrected
commit ca03d6c7d8ec657a6e85e4868ab020d68dc9ffc0
